version: '3'
services:
  php-env:
    build: .
    ports:
      - 8000:80
    # volumes:
    #   - /opt/agenda/php.ini:/usr/local/etc/php/php.ini

  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /opt/agenda/agenda.sql:/docker-entrypoint-initdb.d/agenda.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1

