version: '3'
services:
  php-env:
    build: .
    ports:
      - 8000:80


  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: agenda
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1

